########################################################################################################
#
# MPCE Record Linkage Project
#
# Project: Mapping Print, Charting Enlightenment
#
# Script: Importing data from database, wrangling into a form appropriate for passing to dedupe library
#
# Authors: Michael Falk
#
# Date: 30/10/18
#
########################################################################################################

# Load necessary packages
library(tidyverse) # for data manipulation
library(magrittr) # for a more powerful piping operator
library(DBI) # to enable database connection
library(RMySQL) # a simple API for connecting to a MySQL database

# SECTION 1: ESTABLISH CONNECTION TO DATABASE

# This script supposes that you a running a local copy of the database accessible at 'localhost'.
manuscripts <- dbConnect(MySQL(), user="root", dbname="manuscripts", host="localhost")
info_schema <- dbConnect(MySQL(), user="root", dbname="information_schema", host="localhost")

# Import main datasets.
editions <- manuscripts %>%
  dbSendQuery(paste0("SELECT * FROM manuscript_books_authors ",
                     "LEFT JOIN manuscript_books_editions ",
                     "ON manuscript_books_authors.book_code = manuscript_books_editions.book_code ",
                     "LEFT JOIN manuscript_authors ",
                     "ON manuscript_books_authors.author_code = manuscript_authors.author_code")) %>%
  fetch(n = Inf) %>%
  .[,c(-5,-28)] %>% # delete duplicate columns generated by the queries.
  as_tibble() %>% # convert to tibble for easier manipulation
  select(super_book_code, full_book_title, short_book_titles, translated_title,
         stated_publishers, stated_publication_places, stated_publication_years,
         author_name, author_code) # only keep necessary columns

illegal_titles <- manuscripts %>%
  dbSendQuery("SELECT * FROM manuscript_titles_illegal") %>%
  fetch(n = Inf) %>%
  as_tibble() %>%
  filter(record_status != "DELETED") # filter out deleted records

# Have a look at the two tables:
editions
illegal_titles

# SECTION 2: COMBINE RECORDS INTO SINGLE TABLE

# First clean up the illegal_titles table.
illegal_titles %<>%
  mutate(bastille_imprint_full = gsub("Published in", "", bastille_imprint_full),
         bastille_imprint_full = gsub(", publisher not identified", "", bastille_imprint_full),
         bastille_imprint_full = str_squish(bastille_imprint_full))
